Vagrant.configure("2") do |config|
  config.vm.define "lvmka" do |vm|
    vm.vm.box = "gutehall/ubuntu24-04"
    vm.vm.hostname = "lvmka"

    # Настройки ресурсов
    vm.vm.provider "virtualbox" do |vb|
      vb.name = "diski"
      vb.memory = 2048
      vb.cpus = 2
    end

    # Настройка виртуальных дисков
    vm.vm.provider :virtualbox do |vb|
      sizes = [10, 2, 1, 1]

      sizes.each_with_index do |size, index|
        disk_path = File.expand_path("disk#{index + 1}.vdi", __dir__)

        unless File.exist?(disk_path)
          vb.customize [
            'createhd',
            '--filename', disk_path,
            '--size', size * 1024 
          ]
        end

        vb.customize [
          'storageattach', :id,
          '--storagectl', 'SATA Controller',
          '--port', index + 1,
          '--device', 0,
          '--type', 'hdd',
          '--medium', disk_path
        ]
      end
    end
  end
end

