Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"

  config.vm.hostname = "raiddz"

  # Настройки ресурсов
  config.vm.provider "virtualbox" do |vb|
    vb.name = "multi-disk"
    vb.memory = 1024
    vb.cpus = 1
  end

  # Настройка виртуальных дисков
  config.vm.provider :virtualbox do |vb|
    (1..4).each do |i|
      disk_path = File.expand_path("disk#{i}.vdi", __dir__)

      unless File.exist?(disk_path)
        vb.customize [
          'createhd',
          '--filename', disk_path,
          '--size', 1024
        ]
      end

      vb.customize [
        'storageattach', :id,
        '--storagectl', 'SATA Controller',
        '--port', i,
        '--device', 0,
        '--type', 'hdd',
        '--medium', disk_path
      ]
    end
  end
end

